/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import Entidades.Genero;
import Entidades.Videojuegos;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Negocio.INegocioVideojuegos;

/**
 *
 * @author Gabriel
 */
public class frmPantalla extends javax.swing.JFrame {

    private INegocioVideojuegos NegocioVideojuegos;
    private List<Videojuegos> Listavideojuegos;

    /**
     * Creates new form formPrincipal
     */
    public frmPantalla(INegocioVideojuegos NegocioVideojuegos) {
        initComponents();
        this.NegocioVideojuegos = NegocioVideojuegos;
        if (this.NegocioVideojuegos.obtenerLista() != null) {
            paginas(this.NegocioVideojuegos.obtenerLista().size());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlvideojuegos = new javax.swing.JTable();
        btncrear = new javax.swing.JButton();
        Cbocantidad = new javax.swing.JComboBox<>();
        CboPag = new javax.swing.JComboBox<>();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlvideojuegos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Nombre", "Genero", "Clasificación"
            }
        ));
        jScrollPane1.setViewportView(pnlvideojuegos);

        btncrear.setText("Crear Tablas y Registros");
        btncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearActionPerformed(evt);
            }
        });

        Cbocantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "5" }));
        Cbocantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbocantidadActionPerformed(evt);
            }
        });

        CboPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboPagActionPerformed(evt);
            }
        });

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btncrear, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(14, 14, 14))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(Cbocantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CboPag, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btncrear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CboPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cbocantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void llenarTabla(List<Videojuegos> lista) {
        DefaultTableModel tbl = new DefaultTableModel();
        pnlvideojuegos.setModel(tbl);
        tbl.addColumn("Nombre");
        tbl.addColumn("Clasificacion");
        tbl.addColumn("Genero");

        Object[] datos = new Object[tbl.getColumnCount()];
        for (Videojuegos anime : lista) {

            datos[0] = anime.getNombre();
            datos[1] = anime.getClasificacion();
            datos[2] = anime.getGenero();
            tbl.addRow(datos);
        }
    }
    private void btncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearActionPerformed
        Genero accion = new Genero("Accion");
        Genero aventura = new Genero("Aventura");
        Genero Mature = new Genero("Mature");
        Genero Policiaco = new Genero("Policiaco");
        Genero MMO = new Genero("MMO");
        Videojuegos Halo = new Videojuegos("Halo", "A", accion);
        Videojuegos RE4 = new Videojuegos("Resident Evil 4", "M+", Mature);
        Videojuegos RDR = new Videojuegos("Red dead redemtion", "M", accion);
        Videojuegos RDR2 = new Videojuegos("Red dead redemtion 2", "A", Policiaco);
        Videojuegos Apex = new Videojuegos("Apex legends", "B", accion);
        Videojuegos Zelda = new Videojuegos("Zelda ocarina of time", "E", aventura);
        Videojuegos Mario = new Videojuegos("Mario bros 3", "B", aventura);
        Videojuegos lol = new Videojuegos("League of legends", "E", MMO);
        Videojuegos Halo2 = new Videojuegos("Halo 2", "A", accion);
        Videojuegos Halo3 = new Videojuegos("Halo 3", "A", aventura);
        Videojuegos Halo4 = new Videojuegos("Halo 4", "A", accion);
        Videojuegos Halo3odst = new Videojuegos("Halo 3 odst", "A", accion);
        Videojuegos HaloReach = new Videojuegos("Halo Reach", "A", Mature);
        Videojuegos Halowars = new Videojuegos("Halo Wars", "A", aventura);
        Videojuegos Halowars2 = new Videojuegos("Halo Wars 2", "A", accion);
        Videojuegos Haloinfinite = new Videojuegos("Halo Infinite", "A", Mature);
        Videojuegos Halo5 = new Videojuegos("Halo 5", "A", accion);
        Videojuegos GearsOfWar = new Videojuegos("GearsOfWar ", "A", accion);
        Videojuegos GearsOfWar2 = new Videojuegos("GearsOfWar2 ", "A", Mature);
        Videojuegos GearsOfWar3 = new Videojuegos("GearsOfWar3 ", "A", accion);
        Videojuegos GearsOfWar4 = new Videojuegos("GearsOfWar4 ", "A", Mature);
        List<Videojuegos> lista = new ArrayList<Videojuegos>();
        lista.add(Halo);
        lista.add(RE4);
        lista.add(RDR);
        lista.add(RDR2);
        lista.add(Apex);
        lista.add(Zelda);
        lista.add(lol);
        lista.add(Halo2);
        lista.add(Halo3);
        lista.add(Halo4);
        lista.add(Halo3odst);
        lista.add(HaloReach);
        lista.add(Halowars);
        lista.add(Halowars2);
        lista.add(Haloinfinite);
        lista.add(Halo5);
        lista.add(GearsOfWar);
        lista.add(GearsOfWar2);
        lista.add(GearsOfWar3);
        lista.add(GearsOfWar4);
        if (NegocioVideojuegos.agregaLista(lista) == null) {
            JOptionPane.showMessageDialog(this, "Error al guardar", "MENSAJE DE ERROR", JOptionPane.ERROR_MESSAGE);
        }
        Buscar();
    }//GEN-LAST:event_btncrearActionPerformed

    private void CbocantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbocantidadActionPerformed
        String filtro = txtBuscar.getText();
        if (NegocioVideojuegos.obtenerListaFiltro(filtro) == null) {
            return;
        }
        paginas(NegocioVideojuegos.obtenerListaFiltro(filtro).size());
    }//GEN-LAST:event_CbocantidadActionPerformed

    private void CboPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboPagActionPerformed
        if (CboPag.getSelectedItem() != null) {
            int limite = Integer.parseInt((String) Cbocantidad.getSelectedItem());
            int pagina = Integer.parseInt((String) CboPag.getSelectedItem());
            int offset = (limite * (pagina - 1));
            String filtro = txtBuscar.getText();
            Listavideojuegos = NegocioVideojuegos.obtenerListaFiltro(limite, filtro, offset);
            llenarTabla(Listavideojuegos);
        }


    }//GEN-LAST:event_CboPagActionPerformed
    public void Buscar() {
        String filtro = txtBuscar.getText();
        if (!filtro.equalsIgnoreCase("")) {
            if (NegocioVideojuegos.obtenerListaFiltro(filtro) == null) {
                CboPag.removeAllItems();
                DefaultTableModel defa = new DefaultTableModel();
                defa = (DefaultTableModel) pnlvideojuegos.getModel();
                for (int i = 0; i < defa.getRowCount(); i++) {
                    defa.removeRow(i);
                }

                return;
            }

            paginas(NegocioVideojuegos.obtenerListaFiltro(filtro).size());
        } else {
            paginas(NegocioVideojuegos.obtenerListaFiltro(filtro).size());
            int limite = Integer.parseInt((String) Cbocantidad.getSelectedItem());
            int pagina = Integer.parseInt((String) CboPag.getSelectedItem());
            int offset = (limite * (pagina - 1));
            Listavideojuegos = NegocioVideojuegos.obtenerListaFiltro(limite, filtro, offset);
            llenarTabla(Listavideojuegos);
        }
    }
    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased

    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String texto = txtBuscar.getText();
        Buscar();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed
    public void paginas(int registrosTotales) {
        int limite = Integer.parseInt((String) Cbocantidad.getSelectedItem());
        int paginas = (int) Math.ceil((float) registrosTotales / limite);
        CboPag.removeAllItems();
        for (int i = 1; i <= paginas; i++) {
            CboPag.addItem((String.valueOf(i)));
        }
    }
    ;
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboPag;
    private javax.swing.JComboBox<String> Cbocantidad;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btncrear;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable pnlvideojuegos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
